// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies;

public class Column
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject columnMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestModule.Column";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ColumnId("ColumnId"),
		SeqNbr("SeqNbr"),
		Name("Name"),
		AllowedDropColumnIds("AllowedDropColumnIds"),
		Column_TaskBoard("TestModule.Column_TaskBoard"),
		AllowedDropColumns("TestModule.AllowedDropColumns");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Column(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Column(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject columnMendixObject)
	{
		if (columnMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, columnMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.columnMendixObject = columnMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Column.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testmodule.proxies.Column initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testmodule.proxies.Column.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static testmodule.proxies.Column initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testmodule.proxies.Column(context, mendixObject);
	}

	public static testmodule.proxies.Column load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testmodule.proxies.Column.initialize(context, mendixObject);
	}

	public static java.util.List<testmodule.proxies.Column> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> testmodule.proxies.Column.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ColumnId
	 */
	public final java.lang.Long getColumnId()
	{
		return getColumnId(getContext());
	}

	/**
	 * @param context
	 * @return value of ColumnId
	 */
	public final java.lang.Long getColumnId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ColumnId.toString());
	}

	/**
	 * Set value of ColumnId
	 * @param columnid
	 */
	public final void setColumnId(java.lang.Long columnid)
	{
		setColumnId(getContext(), columnid);
	}

	/**
	 * Set value of ColumnId
	 * @param context
	 * @param columnid
	 */
	public final void setColumnId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long columnid)
	{
		getMendixObject().setValue(context, MemberNames.ColumnId.toString(), columnid);
	}

	/**
	 * @return value of SeqNbr
	 */
	public final java.lang.Integer getSeqNbr()
	{
		return getSeqNbr(getContext());
	}

	/**
	 * @param context
	 * @return value of SeqNbr
	 */
	public final java.lang.Integer getSeqNbr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SeqNbr.toString());
	}

	/**
	 * Set value of SeqNbr
	 * @param seqnbr
	 */
	public final void setSeqNbr(java.lang.Integer seqnbr)
	{
		setSeqNbr(getContext(), seqnbr);
	}

	/**
	 * Set value of SeqNbr
	 * @param context
	 * @param seqnbr
	 */
	public final void setSeqNbr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer seqnbr)
	{
		getMendixObject().setValue(context, MemberNames.SeqNbr.toString(), seqnbr);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of AllowedDropColumnIds
	 */
	public final java.lang.String getAllowedDropColumnIds()
	{
		return getAllowedDropColumnIds(getContext());
	}

	/**
	 * @param context
	 * @return value of AllowedDropColumnIds
	 */
	public final java.lang.String getAllowedDropColumnIds(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AllowedDropColumnIds.toString());
	}

	/**
	 * Set value of AllowedDropColumnIds
	 * @param alloweddropcolumnids
	 */
	public final void setAllowedDropColumnIds(java.lang.String alloweddropcolumnids)
	{
		setAllowedDropColumnIds(getContext(), alloweddropcolumnids);
	}

	/**
	 * Set value of AllowedDropColumnIds
	 * @param context
	 * @param alloweddropcolumnids
	 */
	public final void setAllowedDropColumnIds(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alloweddropcolumnids)
	{
		getMendixObject().setValue(context, MemberNames.AllowedDropColumnIds.toString(), alloweddropcolumnids);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Column_TaskBoard
	 */
	public final testmodule.proxies.TaskBoard getColumn_TaskBoard() throws com.mendix.core.CoreException
	{
		return getColumn_TaskBoard(getContext());
	}

	/**
	 * @param context
	 * @return value of Column_TaskBoard
	 * @throws com.mendix.core.CoreException
	 */
	public final testmodule.proxies.TaskBoard getColumn_TaskBoard(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testmodule.proxies.TaskBoard result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Column_TaskBoard.toString());
		if (identifier != null) {
			result = testmodule.proxies.TaskBoard.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Column_TaskBoard
	 * @param column_taskboard
	 */
	public final void setColumn_TaskBoard(testmodule.proxies.TaskBoard column_taskboard)
	{
		setColumn_TaskBoard(getContext(), column_taskboard);
	}

	/**
	 * Set value of Column_TaskBoard
	 * @param context
	 * @param column_taskboard
	 */
	public final void setColumn_TaskBoard(com.mendix.systemwideinterfaces.core.IContext context, testmodule.proxies.TaskBoard column_taskboard)
	{
		if (column_taskboard == null) {
			getMendixObject().setValue(context, MemberNames.Column_TaskBoard.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Column_TaskBoard.toString(), column_taskboard.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AllowedDropColumns
	 */
	public final java.util.List<testmodule.proxies.Column> getAllowedDropColumns() throws com.mendix.core.CoreException
	{
		return getAllowedDropColumns(getContext());
	}

	/**
	 * @param context
	 * @return value of AllowedDropColumns
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<testmodule.proxies.Column> getAllowedDropColumns(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<testmodule.proxies.Column> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.AllowedDropColumns.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(testmodule.proxies.Column.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of AllowedDropColumns
	 * @param alloweddropcolumns
	 */
	public final void setAllowedDropColumns(java.util.List<testmodule.proxies.Column> alloweddropcolumns)
	{
		setAllowedDropColumns(getContext(), alloweddropcolumns);
	}

	/**
	 * Set value of AllowedDropColumns
	 * @param context
	 * @param alloweddropcolumns
	 */
	public final void setAllowedDropColumns(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<testmodule.proxies.Column> alloweddropcolumns)
	{
		var identifiers = alloweddropcolumns
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.AllowedDropColumns.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return columnMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testmodule.proxies.Column that = (testmodule.proxies.Column) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
