// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the TestModule module
	public static testmodule.proxies.TaskBoardContext dS_TaskBoardContext(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("TestModule.DS_TaskBoardContext").withParams(params).execute(context);
		return result == null ? null : testmodule.proxies.TaskBoardContext.initialize(context, result);
	}
	public static administration.proxies.Account sUB_GetCurrentAccount(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("TestModule.SUB_GetCurrentAccount").withParams(params).execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, result);
	}
	public static testmodule.proxies.TaskBoardContext sUB_TaskBoardContext_GetOrCreate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("TestModule.SUB_TaskBoardContext_GetOrCreate").withParams(params).execute(context);
		return result == null ? null : testmodule.proxies.TaskBoardContext.initialize(context, result);
	}
}